# Constants

token = 'BOT_TOKEN'  # Bot's token

start_command_message = '''Вас приветсвует бот канала @Unilecs! 🖥 Чем я могу вам помочь?🔖'''

help_command_message = '''У меня есть несколько функций! 
Начнем по порядку :
- *Список задач:* я отправлю Вам ссылку на пост с задачами нашего канала.
- *Поиск:* я нахожу задачи по названию или номеру и отправляю Вам ссылки на посты с ними.
- *Книги:* я отправляю вам ссылки на посты с подборками книг от нашего канала.
- *Получить задачу по сложности:* вы выбираете сложность задачи я отправляю вам ссылку на случайную задачу данной сложности.
- *Отправить решение:* в следуйщем сообщении вы отправляете свое решение последней опубликованной  задачи на нашем канале (@UniLecs).
- *Отправить отзыв:* в следующем сообщеении вы отправляете свой отзыв по поводу моей работы, публикации задач на канале @UniLecs и т.д.

**P.S.** Конечно же, лучше всего ознакомиться с функциями можно, опробовав их все😜'''

categories_dict = {
    'Легкие': '*👨🏻‍💼 Легкие задачи:*\n http://telegra.ph/UniLecsLight-07-10',
    'Средние': '*👨🏻‍💻 Задачи среднего уровня:*\n http://telegra.ph/UniLecsMedium-07-10',
    'Сложные': '*👨🏻‍🎓 Сложные задачи:*\n http://telegra.ph/UniLecsHard-07-10',
    'Отмена': 'Вы отменили поиск по категориям. Выберите следующее действие.'
}

books_message = '''*📚 Подборка книг*\n 
*Основы. Часть 1.*
http://telegra.ph/UniLecsBooks-OsnovyCHast1-07-06 \n
*Основы. Часть 2.*
https://telegra.ph/UniLecs-Books-Osnovy-CHast-2-08-24'''

about_command_message = '''Я - бот канала @UniLecs. Предоставляю автоматизированный способ получения задач и не только. Есть вопрос? Вам сюда -> @albert_davletov'''

dict_of_tasks = {
    1: 'http://telegra.ph/Task-1-Vse-li-simvoly-v-stroke-vstrechayutsya-odin-raz-09-20',
    2: 'http://telegra.ph/Task-2-Najti-minimalnyj-ehlement-v-otsortirovannom-po-vozrastaniyu-i-ciklicheski-sdvinutom-massive-09-20',
    3: 'http://telegra.ph/Task-3-Zamenit-vse-probely-v-stroke-simvolami-20-09-21',
    4: 'http://telegra.ph/Task-4-Vyvesti-indeks-zadannogo-ehlementa-v-otsortirovannom-po-vozrastaniyu-i-ciklicheski-sdvinutom-massive-09-22',
    5: 'http://telegra.ph/Task-5-Mozhno-li-stroku-sdelat-palindromom-09-22',
    6: 'http://telegra.ph/Task-6-Opredelit-yavlyaetsya-li-odna-stroka-perestanovkoj-drugoj-09-22',
    7: 'http://telegra.ph/Task-7-Vyvesti-slova-v-stroke-v-poryadke-ubyvaniya-ih-dliny-09-23',
    8: 'http://telegra.ph/Task-8-Vyvesti-maksimalnuyu-summu-ehlementov-v-massive-09-23',
    9: 'http://telegra.ph/Task-9-Zadacha-pro-chisla-Fibonachchi-09-23',
    10: 'http://telegra.ph/Task-10-Obnulenie-matricy-09-23',
    11: 'http://telegra.ph/Task-11-Pervyj-unikalnyj-simvol-v-stroke-09-25',
    12: 'http://telegra.ph/Task-12-Est-li-takie-dva-chisla-v-massive-peremnozhiv-kotorye-my-poluchim-zadannoe-chislo-X-09-26',
    13: 'http://telegra.ph/Task-13-Szhatie-stroki-09-27',
    14: 'http://telegra.ph/Task-14-Vyvesti-slova-v-stroke-v-obratnom-poryadke-10-03',
    15: 'http://telegra.ph/Task-15-Obem-vody-v-gistogramme-10-04',
    16: 'http://telegra.ph/Task-16-Kak-rabotaet-bankomat-10-05',
    17: 'http://telegra.ph/Task-18-Vyvesti-neparnyj-ehlement-v-chislovom-massive-10-07',
    18: 'http://telegra.ph/Task-18-Vyvesti-neparnyj-ehlement-v-chislovom-massive-10-07',
    19: 'http://telegra.ph/Task-19-Najti-slovo-v-simvolnoj-matrice-10-10',
    20: 'http://telegra.ph/Task-20-Stepen-stroki-10-10',
    21: 'http://telegra.ph/Task-21-Najti-otsutstvuyushchij-ehlement-v-massive-10-12',
    22: 'http://telegra.ph/Task-22-Perestanovka-chetnyhnechetnyh-ehlementov-v-massive-10-12',
    23: 'http://telegra.ph/Task-23-Vyvesti-vse-levye-ehlementy-v-binarnom-dereve-10-12',
    24: 'http://telegra.ph/Task-24-Najti-cikl-v-odnosvyaznom-spiske-10-13',
    25: 'http://telegra.ph/Task-25-Najti-ehlement-v-otsortirovannoj-matrice-10-15',
    26: 'http://telegra.ph/Task-26-Preobrazovanie-massiva-putem-proizvedeniya-vseh-znachenij-10-15',
    27: 'http://telegra.ph/Task-27-Operacii-vychitaniya-umnozheniya-i-deleniya-cherez-operaciyu-slozheniya-10-15',
    28: 'http://telegra.ph/Task-28-Stroki-bliznecy-10-18',
    29: 'http://telegra.ph/Task-29-Najti-vse-pary-chisel-v-massive-summa-ktr-ravna-X-10-19',
    30: 'http://telegra.ph/Task-30-Najti-maksimalnyj-ehlement-bez-ispolzovaniya-ifelse-i-drugih-operatorov-sravneniya-10-21',
    31: 'http://telegra.ph/Task-31-Najti-minimalnoe-rasstoyanie-mezhdu-slovami-v-tekste-10-22',
    32: 'http://telegra.ph/Task-32-Najti-nachalo-cikla-v-odnosvyaznom-spiske-10-22',
    33: 'http://telegra.ph/Task-33-Vyvesti-vse-prostye-chisla-do-N-10-22',
    34: 'http://telegra.ph/Task-34-Povernut-matricu-na-90-gradusov-10-22',
    35: 'http://telegra.ph/Task-35-YAvlyaetsya-li-odnosvyaznyj-spisok-palindromom-10-22',
    36: 'http://telegra.ph/Task-35-Edinicy-10-26',
    37: 'http://telegra.ph/Task-37-Kolichestvo-uchastnikov-olimpiady-10-26',
    38: 'http://telegra.ph/Task-38-Maksimalno-vozmozhnoe-chislo-iz-massiva-11-01',
    39: 'http://telegra.ph/Task-39-Najti-summu-vseh-cifr-v-chisle-11-02',
    40: 'http://telegra.ph/Task-40-Proveryaem-chislo-na-prostotu-bez-ciklov-11-02',
    41: 'http://telegra.ph/Task-41-Hanojskie-bashni-11-02',
    42: 'http://telegra.ph/Task-42-Balans-skobok-11-02',
    43: 'http://telegra.ph/Task-43-Korobki-11-12',
    44: 'http://telegra.ph/Task-44-CHasy-s-boem-11-13',
    45: 'http://telegra.ph/Task-45-Plitki-11-13',
    46: 'http://telegra.ph/Task-46-Razvorot-chisla-11-20',
    47: 'http://telegra.ph/Task-47-Raznica-v-kolichestve-bitov-11-29',
    48: 'http://telegra.ph/Task-48-Vybory-11-29',
    49: 'http://telegra.ph/Task-49-Myshka-i-zernyshki-11-30',
    50: 'http://telegra.ph/Task-50-Spichki-11-30',
    51: 'http://telegra.ph/Task-51-Dostavka-zakazov-11-30',
    52: 'http://telegra.ph/Task-52-Putevki-12-09',
    53: 'http://telegra.ph/Task-53-Robot-12-17',
    54: 'http://telegra.ph/Task-54-Okruzhnosti-12-20',
    55: 'http://telegra.ph/Task-55-Kvadraty-12-22',
    56: 'http://telegra.ph/Task-56-CHastichnye-summy-matricy-12-24',
    57: 'http://telegra.ph/Task-57-Parkovka-12-26',
    58: 'http://telegra.ph/Task-58-Formula-1-12-26',
    59: 'http://telegra.ph/Task-59-Zakazy-01-03',
    60: 'http://telegra.ph/Task-60-Slozhenie-svyaznyh-spiskov-01-08',
    61: 'http://telegra.ph/Task-61-Dorozhnaya-sluzhba-01-11',
    62: 'http://telegra.ph/Task-62-Podarki-01-15',
    63: 'http://telegra.ph/Task-63-NOK---naimenshee-obshchee-kratnoe-01-19',
    64: 'http://telegra.ph/Task-64-Odinakovyj-perimetr-01-22',
    65: 'http://telegra.ph/Task-65-Ploshchad-trapecij-01-25',
    66: 'http://telegra.ph/Task-66-Stepen-dvojki-01-30',
    67: 'http://telegra.ph/Task-67-Kolichestvo-tochek-02-02',
    68: 'http://telegra.ph/Task-68-Dve-cifry-02-05',
    69: 'http://telegra.ph/Task-69-Kolichestvo-nulej-v-konce-faktoriala-02-06',
    70: 'http://telegra.ph/Task-70-Pryamoj-ugol-02-07',
    71: 'http://telegra.ph/Task-71-Kak-pravilno-polivat-derevya-v-sadu-02-13',
    72: 'http://telegra.ph/Task-72-Vozvodim-v-stepen-02-18',
    73: 'http://telegra.ph/Task-73-Tri-edinicy-02-21',
    74: 'http://telegra.ph/Task-74-Nesokratimaya-drob-02-25',
    75: 'http://telegra.ph/Task-75-Tumblery-02-26',
    76: 'http://telegra.ph/Task-76-Perestanovka-massiva-03-06',
    77: 'http://telegra.ph/Task-77-Ploshchad-chetyrehugolnika-03-07',
    78: 'http://telegra.ph/Task-78-Cifrovoj-koren-chisla-03-11',
    79: 'http://telegra.ph/Task-79-Gistogramma-03-12',
    80: 'http://telegra.ph/Task-80-Dvoichnoe-derevo-poiska-03-12',
    81: 'http://telegra.ph/Task-81-Faktorizaciya-chisla-03-21',
    82: 'http://telegra.ph/Task-82-Uravnenie-03-26',
    83: 'http://telegra.ph/Task-83-Uravnenie-2-04-03',
    84: 'http://telegra.ph/Task-84-Anagrammy-03-30',
    85: 'http://telegra.ph/Task-85-Nezakonchennaya-formula-04-12',
    86: 'http://telegra.ph/Task-86-Sem-raz-otmer-odin-raz-otrezh-04-17',
    87: 'http://telegra.ph/Task-87-Postroenie-04-23',
    88: 'http://telegra.ph/Task-88-Binomialnyj-koehfficient-04-24',
    89: 'http://telegra.ph/Task-89-Sejf-04-29',
    90: 'http://telegra.ph/Task-90-Gryadki-04-30',
    91: 'http://telegra.ph/Task-91-Obrabotka-massiva-05-03',
    92: 'http://telegra.ph/Task-92-Sistema-uravnenij-05-08',
    93: 'http://telegra.ph/Task-93-Ochered-za-biletami-05-11',
    94: 'http://telegra.ph/Task-94-Pirog-05-15',
    95: 'http://telegra.ph/Task-95-Ploshchad-vydelennoj-oblasti-05-17',
    96: 'http://telegra.ph/Task-96-Peresechenie-05-22',
    97: 'http://telegra.ph/Task-97-Mesto-v-stroyu-05-24',
    98: 'http://telegra.ph/Task-97-Mesto-v-stroyu-05-24',
    99: 'http://telegra.ph/Task-99-Neprostaya-sortirovka-06-01',
    100: 'http://telegra.ph/Task-100-Ovoshchnaya-tarelka-06-03',
    101: 'http://telegra.ph/Task-101-Mazhoritarnyj-ehlement-massiva-06-11',
    102: 'http://telegra.ph/Task-102-Minimalnoe-kol-vo-operacij-06-13',
    103: 'http://telegra.ph/Task-103-Kolichestvo-peresechenij-06-18',
    104: 'http://telegra.ph/Task-104-Koshki---myshki-06-25',
    105: 'http://telegra.ph/Task-105-Kvartalnye-ocenki-06-26',
    106: 'http://telegra.ph/Task-106-CHastichnaya-summa-06-29',
    107: 'https://telegra.ph/Task-107-Osnovy-grafov-07-08',
    108: 'https://telegra.ph/Task-108-Teoriya-mnozhestv-07-16',
    109: 'https://telegra.ph/Task-109-Mediana-i-srednee-arifmeticheskoe-07-17',
    110: 'https://telegra.ph/UniLecs-110-Budni-brakonera-07-20',
    111: 'https://telegra.ph/UniLecs-111-Final-07-24',
    112: 'https://telegra.ph/UniLecs-112-Soveshchanie-07-29',
    113: 'https://telegra.ph/UniLecs-113-Inicializaciya-massiva-07-31',
    114: 'https://telegra.ph/UniLecs-114-Tetrad-v-kletochku-08-02',
    115: 'https://telegra.ph/UniLecs-115-CHempionat-08-06',
    116: 'https://telegra.ph/UniLecs-116-Vagonetka-08-13',
    117: 'https://telegra.ph/UniLecs-117-Snova-stepen-08-13',
    118: 'https://telegra.ph/UniLecs-118-Summa-na-dereve-08-20',
    119: 'https://telegra.ph/UniLecs-119-Sedlovoj-ehlement-matricy-08-20',
    120: 'https://telegra.ph/UniLecs-120-Liniya-Fronta-08-24',
    121: 'https://telegra.ph/UniLecs-121-cAPS-LOCK-08-27',
    122: 'https://telegra.ph/Anons-122-Maksimalnaya-podmatrica-08-31',
}

dict_of_names = {
    1: 'Все ли символы в строке встречаются один раз',
    2: 'Найти минимальный элемент в отсортированном по возрастанию и циклически сдвинутом массиве',
    3: "Заменить все пробелы в строке символами '%20'",
    4: 'Вывести индекс заданного элемента в отсортированном по возрастанию и циклически сдвинутом массиве',
    5: 'Можно ли строку сделать палиндромом',
    6: 'Определить является ли одна строка перестановкой другой',
    7: 'Вывести слова в строке в порядке убывания их длины',
    8: 'Вывести максимальную сумму элементов в массиве',
    9: 'Задача про числа Фибоначчи',
    10: 'Обнуление матрицы',
    11: 'Первый уникальный символ в строке',
    12: 'Есть ли такие два числа в массиве, перемножив которые мы получим заданное число X',
    13: 'Сжатие строки',
    14: 'Вывести слова в строке в обратном порядке',
    15: 'Объем воды в гистограмме',
    16: 'Как работает банкомат ?!',
    17: 'Поменять значения двух переменных без использования третьей',
    18: 'Вывести непарный элемент в числовом массиве',
    19: 'Найти слово в символьной матрице',
    20: 'Степень строки',
    21: 'Найти отсутствующий элемент в массиве',
    22: 'Перестановка четных/нечетных элементов в массиве',
    23: 'Вывести все левые элементы в бинарном дереве',
    24: 'Найти цикл в односвязном списке',
    25: 'Найти элемент в отсортированной матрице',
    26: 'Преобразование массива путем произведения всех значений',
    27: 'Операции вычитания, умножения и деления через операцию сложения',
    28: 'Строки "близнецы"',
    29: 'Найти все пары чисел в массиве, сумма которых равна',
    30: 'Найти максимальный элемент без использования if/else и других операторов сравнения',
    31: 'Найти минимальное расстояние между словами в тексте',
    32: 'Найти начало цикла в односвязном списке',
    33: 'Вывести все простые числа до N',
    34: 'Повернуть матрицу на 90 градусов',
    35: 'Является ли односвязный список палиндромом',
    36: 'Единицы',
    37: 'Количество участников олимпиады',
    38: 'Максимально возможное число из массива',
    39: 'Найти сумму всех цифр в числе (без циклов)',
    40: 'Проверяем число на простоту без циклов',
    41: 'Ханойские башни',
    42: 'Баланс скобок',
    43: 'Коробки',
    44: 'Часы с боем',
    45: 'Положить плитку',
    46: 'Разворот числа',
    47: 'Разворот числа',
    48: 'Выборы',
    49: 'Мышка и зернышки',
    50: 'Спички',
    51: 'Доставка заказов',
    52: 'Путевки',
    53: 'Робот',
    54: 'Окружности',
    55: 'Квадраты',
    56: 'Частичные суммы матрицы',
    57: 'Парковка',
    58: 'Формула 1',
    59: 'Заказы',
    60: '"Сложение" связных списков',
    61: 'Дорожная служба',
    62: 'Подарки',
    63: 'НОК',
    64: 'Одинаковый периметр',
    65: 'Площадь многоугольника',
    66: 'Степень двойки',
    67: 'Количество точек',
    68: 'Две цифры',
    69: 'Количество нулей в конце факториала',
    70: 'Прямой угол',
    71: 'Как правильно поливать дерево',
    72: 'Возводим в степень',
    73: 'Три единицы',
    74: 'Несократимая дробь',
    75: 'Тумблеры',
    76: 'Перестановка массива',
    77: 'Площадь четырехугольника',
    78: 'Цифровой корень числа',
    79: 'Гистограмма',
    80: 'Двоичное дерево поиска',
    81: 'Факторизация числа',
    82: 'Уравнение',
    83: 'Уравнение 2',
    84: 'Анаграммы',
    85: 'Незаконченная формула',
    86: 'Семь раз отмерь, один раз отрежь',
    87: 'Построение',
    88: 'Биномиальный коэффициент',
    89: 'Сейф',
    90: 'Грядки',
    91: 'Обработка массива',
    92: 'Система уравнений',
    93: 'Очередь за билетами',
    94: 'Пирог',
    95: 'Площадь выделенной области',
    96: 'Пересечение',
    97: 'Место в строю',
    98: 'Количество взвешиваний ',
    99: 'Непростая сортировка',
    100: 'Овощная нарезка',
    101: 'Мажоритарный элемент',
    102: 'Минимальное кол-во операций',
    103: 'Количество пересечений',
    104: 'Кошки-мышки',
    105: 'Квартальные оценки',
    106: 'Частичная сумма',
    107: 'Основы графов',
    108: 'Теория множеств',
    109: 'Медиана и среднее арифметическое',
    110: 'Будни браконьера',
    111: 'Финал',
    112: 'Совещание',
    113: 'Инициализация массива',
    114: 'Тетрадь в клеточку',
    115: 'Чемпионат',
    116: 'Вагонетка',
    117: 'Снова степень',
    118: 'Сумма на дереве',
    119: 'Седловой элемент матрицы',
    120: 'Линия Фронта',
    121: 'cAPS LOCK',
    122: 'Максимальная подматрица'
}